name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [published]

jobs:
  release:
    name: Build and Publish NuGet Package
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Extract version from tag
      id: version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION="1.0.0-preview.${GITHUB_RUN_NUMBER}"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
        
    - name: Restore dependencies
      run: dotnet restore Noundry.Assertive.sln
      
    - name: Build solution
      run: dotnet build Noundry.Assertive.sln --configuration Release --no-restore
      
    - name: Run tests
      run: dotnet test Noundry.Assertive.sln --configuration Release --no-build --verbosity normal
      
    - name: Pack NuGet package
      run: dotnet pack src/Noundry.Assertive/Noundry.Assertive.csproj --configuration Release --no-build --output ./artifacts -p:PackageVersion=${{ steps.version.outputs.VERSION }}
      
    - name: Publish to NuGet.org
      if: github.event_name == 'release'
      run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
    - name: Publish to GitHub Packages
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/noundry/index.json --skip-duplicate
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./artifacts/*.nupkg
        retention-days: 30